stages:
  fetch_audioset_train:
    cmd: "
      rm -rf 
        ./datasets/audioset_train_mel_split/
        ./datasets/audioset_metadata/
      && python -m swarm.download.kaggle
        --kaggle_dataset zfturbo/audioset
        --temp_dir ./temp/audioset_train/
        --unzip False
      && python -m swarm.preprocess.audioset
        --input_zip ./temp/audioset_train/audioset.zip
        --output_dir_lms ./datasets/audioset_train_mel_split/
        --output_dir_metadata ./datasets/audioset_metadata/
        --temp_dir ./temp/audioset_train/
    "
    deps:
      - src/swarm/download/kaggle.py
      - src/swarm/preprocess/tools.py
      - src/swarm/preprocess/audioset.py
      - src/swarm/configs/spectrograms.py
    params:
      - spectrogram
    outs:
      - ./datasets/audioset_train_mel_split/
      - ./datasets/audioset_metadata/class_labels_indices.csv
      - ./datasets/audioset_metadata/train.csv
  fetch_gtzan:
    cmd: "
      rm -rf 
        ./temp/gtzan/
        ./datasets/gtzan_train_mel_split/
        ./datasets/gtzan_val_mel_split/
      && python -m swarm.download.kaggle
        --kaggle_dataset andradaolteanu/gtzan-dataset-music-genre-classification
        --temp_dir ./temp/gtzan/
        --output_dir ./temp/gtzan_wavs/
        --unzip True
      && python -m swarm.preprocess.gtzan
        --input_dir ./temp/gtzan_wavs/
        --output_dir_train ./datasets/gtzan_train_mel_split/
        --output_dir_val ./datasets/gtzan_val_mel_split/
      && rm -rf ./temp/gtzan/
    "
    deps:
      - src/swarm/download/kaggle.py
      - src/swarm/preprocess/tools.py
      - src/swarm/preprocess/gtzan.py
      - src/swarm/configs/spectrograms.py
    params:
      - spectrogram
      - datasets.gtzan
    outs:
      - ./datasets/gtzan_train_mel_split/
      - ./datasets/gtzan_val_mel_split/
  train_barlow_twins:
    cmd: "
      rm -f ./models/model.pth ./models/model.json
      && python -m swarm.train
        --train_dir datasets/gtzan_train_mel_split
        --audio_dir datasets/audioset_train_mel_split
        --audioset_train_csv_path datasets/audioset_metadata/train.csv
        --audioset_class_labels_indices_csv_path datasets/audioset_metadata/class_labels_indices.csv
        --model_path ./models/model.pth
    "
    deps:
      - src/swarm/augmentations.py
      - src/swarm/callbacks.py
      - src/swarm/configs/dataset_gtzan.py
      - src/swarm/datasets.py
      - src/swarm/losses.py
      - src/swarm/models.py
      - src/swarm/train.py
      - src/swarm/utils.py
      - ./datasets/gtzan_train_mel_split/
      - ./datasets/audioset_train_mel_split/
      - ./datasets/audioset_metadata/class_labels_indices.csv
      - ./datasets/audioset_metadata/train.csv
    params:
      - training
      - augmentations
      - datasets.gtzan
    outs:
      - ./models/model.pth
      - ./models/model.json
  train_linear_eval:
    cmd: "
      rm -rf ./models/linear_eval_model.pth
      && python -m swarm.linear_eval
        --model_path ./models/model.pth
        --gtzan_path_train ./datasets/gtzan_train_mel_split
        --linear_eval_model_path ./models/linear_eval_model.pth
    "
    deps:
      - src/swarm/augmentations.py
      - src/swarm/configs/augmentations.py
      - src/swarm/configs/training.py
      - src/swarm/datasets.py
      - src/swarm/models.py
      - src/swarm/losses.py
      - src/swarm/linear_eval.py
      - src/swarm/utils.py
      - ./models/model.pth
      - ./models/model.json
      - ./datasets/gtzan_train_mel_split/
    params:
      - training
      - augmentations
      - datasets.gtzan
    outs:
      - ./models/linear_eval_model.pth
  test_linear_model:
    cmd: "
      python -m swarm.test
        --model_path ./models/model.pth
        --gtzan_path_test ./datasets/gtzan_val_mel_split
        --linear_eval_model_path ./models/linear_eval_model.pth
    "
    deps:
      - src/swarm/test.py
      - src/swarm/configs/augmentations.py
      - ./models/model.pth
      - ./models/model.json
      - ./models/linear_eval_model.pth
      - ./datasets/gtzan_val_mel_split/