
spectrogram:
  target_sample_rate: 16000
  n_mels: 64
  f_min: 60
  f_max: 7800

datasets:
  gtzan:
    train_val_split: 0.8
    segment_length_sec: 10.0
    hop_length_sec: 10.0
    num_classes: 10
  
training:
  batch_size: 128
  val_split: 0.1
  lr: 0.000001642
  xcorr_lambda: 1.033
  emb_dim_size: 1024
  early_stopping_patience: 10
  max_epochs: 50

augmentations:
  random_crop_width:
    target_frames: 96
  mixup:
    ratio: 0.243
    memory_size: 2048
  linear_fader:
    gain: 0.727
  random_resize_crop:
    crop_scale:
      min: 1.0
      max: 1.361
    freq_scale:
      min: 0.596
      max: 1.174
    time_scale:
      min: 0.901
      max: 1.462