
spectrogram:
  target_sample_rate: 16000
  n_mels: 64
  f_min: 60
  f_max: 7800

datasets:
  gtzan:
    train_val_split: 0.8
    segment_length_sec: 10.0
    hop_length_sec: 10.0
    num_classes: 10
  
training:
  batch_size: 512
  val_split: 0.1
  lr: 0.00005
  xcorr_lambda: 0.005
  emb_dim_size: 4096

augmentations:
  random_crop_width:
    target_frames: 96
  mixup:
    ratio: 0.4
    memory_size: 2048
  linear_fader:
    gain: 1.0
  random_resize_crop:
    crop_scale:
      min: 1.0
      max: 1.5
    freq_scale:
      min: 0.6
      max: 1.5
    time_scale:
      min: 0.6
      max: 1.5